import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';


const UserPage = () => {
    const storedNotes = [{id:1, name:'Testing Notes'},{id:2, name:'Getting into Notes'},{id:3, name:'Mores tests'},{id:4, name:'Testing Notes'},{id:5, name:'Getting into Notes'},{id:6, name:'Mores tests'}];
    const router = useRouter();
    

    const loadNote = (noteId ,event) => {
        event.preventDefault();
        const url = `/${router.query.user}/${noteId}`;
        router.push(url); 
    }

    return (
        <>
            <Head>
            <title>Flow</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>User ID or Something</h1>

                <div className='row m-4'>
                    {storedNotes.map((notes) => 
                        <button className='col-2 border border-primary rounded-3 m-2 text-center' key={notes.id} onClick={(event) => loadNote(notes.id, event)}>
                            {notes.name}
                        </button>
                    )}

                    <button className='col-12 border border-primary rounded-3 mt-5 text-center' onClick={(event) => loadNote(7, event)}>{'Create New Note'}</button>
                </div>
            </main>
        </>
    );
}

export default UserPage;