import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';


const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  const router = useRouter();

  const loadUserPage = (event) => {
    event.preventDefault();
    const userId = 47839579032709;
    const url = `/${userId}`;
    router.replace(url); //Disables back button or something
  }

  return (
    <>
      <Head>
        <title>Flow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Login</h1>
        <div>
          <form onSubmit={loadUserPage}>
            <label className="pb-3" htmlFor="username">Username
              <input type="text" name="username" />
            </label>
            <br></br>
            <label htmlFor="password">Password
              <input type="password" name="password" />
            </label>
            <br></br>
            <button type="submit">Sumbit</button>
          </form>
        </div>
      </main>
    </>
  )
}

export default Home;